export const LOGIN_FORM_SUBMIT: 'LOGIN_FORM_SUBMIT' = 'LOGIN_FORM_SUBMIT';
export const LOGIN_FORM_SUBMIT_SUCCEED: 'LOGIN_FORM_SUBMIT_SUCCEED' =
  'LOGIN_FORM_SUBMIT_SUCCEED';
export const LOGIN_FORM_SUBMIT_FAILED: 'LOGIN_FORM_SUBMIT_FAILED' =
  'LOGIN_FORM_SUBMIT_FAILED';
