export const PLACE_ORDER_REQUEST_STARTED:'PLACE_ORDER_REQUEST_STARTED' = 'PLACE_ORDER_REQUEST_STARTED';
export const PLACE_ORDER_REQUEST_SUCCEED:'PLACE_ORDER_REQUEST_SUCCEED' = 'PLACE_ORDER_REQUEST_SUCCEED';
export const PLACE_ORDER_REQUEST_FAILED:'PLACE_ORDER_REQUEST_FAILED' = 'PLACE_ORDER_REQUEST_FAILED';

export const OPEN_ORDER_DETAILS_MODAL:'OPEN_ORDER_DETAILS_MODAL' = 'OPEN_ORDER_DETAILS_MODAL';
export const CLOSE_ORDER_DETAILS_MODAL:'CLOSE_ORDER_DETAILS_MODAL' = 'CLOSE_ORDER_DETAILS_MODAL';
