export const EDIT_PROFILE_FORM_SUBMIT:'EDIT_PROFILE_FORM_SUBMIT' = 'EDIT_PROFILE_FORM_SUBMIT';
export const EDIT_PROFILE_FORM_SUBMIT_SUCCEED:'EDIT_PROFILE_FORM_SUBMIT_SUCCEED' =
    'EDIT_PROFILE_FORM_SUBMIT_SUCCEED';
export const EDIT_PROFILE_FORM_SUBMIT_FAILED:'EDIT_PROFILE_FORM_SUBMIT_FAILED' =
    'EDIT_PROFILE_FORM_SUBMIT_FAILED';

export const GET_USER_REQUEST_STARTED:'GET_USER_REQUEST_STARTED' = 'GET_USER_REQUEST_STARTED';
export const GET_USER_REQUEST_SUCCEED:'GET_USER_REQUEST_SUCCEED' = 'GET_USER_REQUEST_SUCCEED';
export const GET_USER_REQUEST_FAILED:'GET_USER_REQUEST_FAILED' = 'GET_USER_REQUEST_FAILED';

export const REFRESH_TOKEN_REQUEST_STARTED:'REFRESH_TOKEN_REQUEST_STARTED' = 'REFRESH_TOKEN_REQUEST_STARTED';
export const REFRESH_TOKEN_REQUEST_SUCCEED:'REFRESH_TOKEN_REQUEST_SUCCEED' = 'REFRESH_TOKEN_REQUEST_SUCCEED';
export const REFRESH_TOKEN_REQUEST_FAILED:'REFRESH_TOKEN_REQUEST_FAILED' = 'REFRESH_TOKEN_REQUEST_FAILED';

export const LOGOUT_REQUEST_STARTED:'LOGOUT_REQUEST_STARTED' = 'LOGOUT_REQUEST_STARTED';
export const LOGOUT_REQUEST_SUCCEED:'LOGOUT_REQUEST_SUCCEED' = 'LOGOUT_REQUEST_SUCCEED';
export const LOGOUT_REQUEST_FAILED:'LOGOUT_REQUEST_FAILED' = 'LOGOUT_REQUEST_FAILED';
